import bostonUniversityLogo from './assets/schools/boston-university.gif'
import universityOfArizonaLogo from './assets/schools/university-of-arizona.svg'

export const profile = {
  name: 'Kimi',
  fullName: 'Kimi Chen',
  chineseName: '陈俊哲',
  initials: 'KC',
  eyebrow: 'KIMI CHEN · AI ENGINEERING',
  role: 'AI Application Development Engineer',
  roleZh: 'AI 应用开发工程师',
  location: '福建福州 · 支持英文工作交流',
  email: 'chen.junzhe2000@qq.com',
  availability: 'AI 应用开发工程师 · 开放工作机会',
  heroLines: ['AI SYSTEMS', 'REAL IMPACT'],
  heroTaglineZh: '构建智能系统 · 创造真实价值',
  intro:
    '计算机科学硕士，专注大模型应用、模型微调部署与机器学习，用工程方法把 AI 能力转化为可落地的产品。',
  aboutKicker: 'FROM MODEL TO PRODUCT',
  aboutKickerZh: '从模型到产品',
  aboutHeadline: ['BUILDING AI', 'THAT WORKS.'],
  aboutHeadlineZh: '以工程思维，让 AI 能力成为稳定、清晰、真正可用的产品。',
  about:
    '我拥有计算机科学与数学的交叉背景，专注大模型应用、机器学习和算法工程。我擅长把复杂问题拆解成清晰、可执行的工作流。',
  philosophy:
    '从数据处理、模型训练与评估，到 Agentic RAG、LoRA 微调、vLLM 推理服务和交互原型，我关注从模型能力到产品体验的完整落地。',
  stats: [
    { value: '03+', label: 'AI / ML PROJECTS', labelZh: '重点 AI / 算法项目' },
    { value: '83%+', label: 'PREDICTION AUC', labelZh: '预测模型 AUC' },
    { value: '06+', label: 'YEARS IN THE U.S.', labelZh: '美国学习生活经历' },
  ],
  education: [
    {
      code: 'BU',
      logo: bostonUniversityLogo,
      school: 'BOSTON UNIVERSITY',
      schoolZh: '波士顿大学',
      period: '2024.09 — 2025.12',
      degree: 'M.S. IN COMPUTER SCIENCE',
      degreeZh: '计算机科学硕士',
      focus: ['Algorithms', 'Machine Learning', 'Operating Systems', 'MySQL'],
      statement: '从算法原理到模型工程，建立面向真实系统的计算机科学训练。',
      accent: '#4d68ff',
    },
    {
      code: 'UA',
      logo: universityOfArizonaLogo,
      school: 'UNIVERSITY OF ARIZONA',
      schoolZh: '亚利桑那大学',
      period: '2019.09 — 2023.12',
      degree: 'B.S. IN MATHEMATICS',
      degreeZh: '数学学士',
      focus: ['Linear Algebra', 'Discrete Math', 'Numerical Analysis', 'Formal Languages'],
      statement: '以数学和逻辑为基础，形成严谨的问题拆解与建模能力。',
      award: 'INTERNATIONAL TUITION AWARD · 2020—2023',
      accent: '#d9ff67',
    },
  ],
  projects: [
    {
      number: '01',
      title: 'LESSON PLAN AGENT',
      titleZh: '教案生成智能体',
      type: 'AGENTIC RAG / AI APPLICATION',
      typeZh: '智能体工作流 / AI 应用',
      year: '2025',
      summary: '基于 Dify 搭建多阶段教案生成工作流，以向量检索、重排序和结构化提示词自动产出可编辑教案初稿。',
      tags: ['Dify', 'Agentic RAG', 'BGE'],
      color: '#4d68ff',
      href: 'https://github.com/KimiChen2000',
    },
    {
      number: '02',
      title: 'LLAMA SUMMARIZATION',
      titleZh: 'Llama 文本摘要模型',
      type: 'FINE-TUNING / INFERENCE',
      typeZh: '模型微调 / 推理部署',
      year: '2025',
      summary: '完成数据标准化、LoRA 微调、BLEU/ROUGE 评测，并使用 vLLM 与 Docker 部署 OpenAI 兼容推理接口。',
      tags: ['LLaMA-Factory', 'LoRA', 'vLLM'],
      color: '#e5ff45',
      href: 'https://github.com/KimiChen2000',
    },
    {
      number: '03',
      title: 'DOTA2 MATCH PREDICTOR',
      titleZh: 'DOTA2 胜负预测',
      type: 'MACHINE LEARNING / KAGGLE',
      typeZh: '机器学习 / Kaggle',
      year: '2025',
      summary: '围绕对局前五分钟数据构建差值特征，对比多种分类模型，优化后受试者工作特征曲线下面积超过 83%。',
      tags: ['Python', '特征工程', '随机森林'],
      color: '#ff7657',
      href: 'https://github.com/KimiChen2000',
    },
  ],
  capabilities: [
    {
      number: '01',
      title: 'AI APPLICATIONS',
      titleZh: 'AI 应用与智能体',
      description: 'Dify、Agentic RAG、Prompt Engineering、结构化输出',
    },
    {
      number: '02',
      title: 'MODEL ENGINEERING',
      titleZh: '模型微调与部署',
      description: 'LLaMA-Factory、LoRA、PyTorch、vLLM、Docker',
    },
    {
      number: '03',
      title: 'ALGORITHM & FULL-STACK',
      titleZh: '算法与全栈开发',
      description: 'Python、机器学习、MySQL、React、JavaScript',
    },
  ],
  experience: [
    {
      period: '2024.09 — 2025.12',
      company: 'BOSTON UNIVERSITY',
      companyZh: '波士顿大学',
      role: 'M.S. IN COMPUTER SCIENCE',
      roleZh: '计算机科学硕士',
    },
    {
      period: '2024.05 — 2024.08',
      company: 'FUCHANG WEIKONG',
      companyZh: '福建富昌维控',
      role: 'ALGORITHM ENGINEER INTERN',
      roleZh: '算法工程师实习',
    },
    {
      period: '2019.09 — 2023.12',
      company: 'UNIVERSITY OF ARIZONA',
      companyZh: '亚利桑那大学',
      role: 'B.S. IN MATHEMATICS',
      roleZh: '数学学士',
    },
  ],
  socials: [
    { label: 'GitHub', href: 'https://github.com/KimiChen2000' },
    { label: 'Email', href: 'mailto:chen.junzhe2000@qq.com' },
  ],
}
